import path from "path";
import fs from "fs-extra";
import chalk from "chalk";
import { detectTailwindMajor, warnIfUntrustedRegistry } from "./add";
import { loadRegistryEntries } from "./list";
import { loadRegistryInfo } from "./info";

type ThemeFormat = "v3" | "v4" | "auto";

type ThemeOptions = {
    url: string;
    component?: string;
    format: ThemeFormat;
    out?: string;
};

type Item = {
    name: string;
    tailwindConfig?: Record<string, unknown>;
    tailwindCss?: string;
};

async function resolveFormat(format: ThemeFormat): Promise<"v3" | "v4"> {
    if (format !== "auto") return format;
    let cssPath: string | undefined;
    try {
        const config = await fs.readJson("components.json");
        cssPath = config?.tailwind?.css;
    } catch {
        // No components.json — fall back to filesystem heuristics only.
    }
    const major = detectTailwindMajor(process.cwd(), cssPath);
    if (major === "v4") return "v4";
    return "v3";
}

async function gatherItems(options: ThemeOptions): Promise<Item[] | null> {
    if (options.component) {
        const record = await loadRegistryInfo(options.url, options.component);
        if (!record) return null;
        return [{
            name: record.item.name,
            tailwindConfig: record.item.tailwindConfig,
            tailwindCss: record.item.tailwindCss,
        }];
    }
    const entries = await loadRegistryEntries(options.url);
    if (!entries) return null;
    // Parallel fetch — a typical registry has dozens of components, and
    // serial requests turned the no-component path into a multi-second wait.
    const records = await Promise.all(entries.map((e) => loadRegistryInfo(options.url, e.name)));
    return records
        .filter((r): r is NonNullable<typeof r> => r !== null)
        .map((r) => ({
            name: r.item.name,
            tailwindConfig: r.item.tailwindConfig,
            tailwindCss: r.item.tailwindCss,
        }));
}

function isObject(v: unknown): v is Record<string, unknown> {
    return v !== null && typeof v === "object" && !Array.isArray(v);
}

export function aggregateV3(items: Item[]): { animation: Record<string, string>; keyframes: Record<string, unknown> } {
    const animation: Record<string, string> = {};
    const keyframes: Record<string, unknown> = {};
    for (const item of items) {
        const extend = (item.tailwindConfig?.theme as { extend?: Record<string, unknown> } | undefined)?.extend;
        if (!extend) continue;
        const a = extend.animation;
        if (isObject(a)) {
            for (const [k, v] of Object.entries(a)) {
                if (typeof v === "string" && !(k in animation)) animation[k] = v;
            }
        }
        const k = extend.keyframes;
        if (isObject(k)) {
            for (const [name, frames] of Object.entries(k)) {
                if (!(name in keyframes)) keyframes[name] = frames;
            }
        }
    }
    return { animation, keyframes };
}

export function formatV3Preset(items: Item[]): string {
    const { animation, keyframes } = aggregateV3(items);
    const lines: string[] = [];
    lines.push("// Paste into your tailwind.config.{js,ts} under `theme.extend`.");
    lines.push("// Generated by `uniqueui theme` — safe to re-run; existing keys win.");
    lines.push("module.exports = {");
    lines.push("  theme: {");
    lines.push("    extend: {");
    lines.push(`      animation: ${JSON.stringify(animation, null, 2).replace(/\n/g, "\n      ")},`);
    lines.push(`      keyframes: ${JSON.stringify(keyframes, null, 2).replace(/\n/g, "\n      ")},`);
    lines.push("    },");
    lines.push("  },");
    lines.push("};");
    return lines.join("\n");
}

export function formatV4Snippet(items: Item[]): string {
    const lines: string[] = [
        "/* Paste into your globals.css (the file at components.json#tailwind.css). */",
        "/* Generated by `uniqueui theme` — each block is wrapped in the same markers `uniqueui add` uses, so re-runs are idempotent. */",
        "",
    ];
    for (const item of items) {
        if (!item.tailwindCss) continue;
        lines.push(`/* uniqueui:start ${item.name} */`);
        lines.push(item.tailwindCss.trimEnd());
        lines.push(`/* uniqueui:end ${item.name} */`);
        lines.push("");
    }
    return lines.join("\n");
}

export async function theme(options: ThemeOptions): Promise<void> {
    warnIfUntrustedRegistry(options.url);
    const format = await resolveFormat(options.format);
    const items = await gatherItems(options);
    if (!items || items.length === 0) {
        console.error(
            chalk.red(
                options.component
                    ? `Component "${options.component}" not found at ${options.url}.`
                    : `No registry components found at ${options.url}.`,
            ),
        );
        process.exitCode = 1;
        return;
    }

    if (format === "v4" && items.every((i) => !i.tailwindCss)) {
        console.error(
            chalk.yellow(
                options.component
                    ? `Component "${options.component}" ships no v4 tailwindCss snippet. Try --format v3.`
                    : "No registry components ship a v4 tailwindCss snippet. Try --format v3.",
            ),
        );
        process.exitCode = 1;
        return;
    }
    if (format === "v3" && items.every((i) => !i.tailwindConfig)) {
        console.error(
            chalk.yellow(
                options.component
                    ? `Component "${options.component}" ships no v3 tailwindConfig. Try --format v4.`
                    : "No registry components ship a v3 tailwindConfig. Try --format v4.",
            ),
        );
        process.exitCode = 1;
        return;
    }

    const output = format === "v4" ? formatV4Snippet(items) : formatV3Preset(items);

    if (options.out) {
        await fs.ensureDir(path.dirname(path.resolve(options.out)));
        await fs.writeFile(options.out, output, "utf8");
        console.log(chalk.green(`Wrote ${format} theme (${items.length} component(s)) to ${options.out}`));
        return;
    }
    console.log(output);
}
