// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import fs from "fs";
import path from "path";
import { describe, expect, it } from "vitest";
import { componentsList } from "../config/components";
import { componentDemos } from "../config/demos";
import { docsScenarios } from "../config/docs-scenarios";
import { registryComponentSlugs } from "../config/component-registry";

type RegistryDocsManifest = {
  components: Array<{
    slug: string;
    docs?: {
      overview?: string;
      scenarios?: Array<{
        title: string;
        description: string;
        code: string;
      }>;
    };
  }>;
};

describe("Component metadata sync", () => {
  it("keeps docs components and registry component slugs aligned", () => {
    const docsSlugs = componentsList.map((component) => component.slug).sort();
    const registrySlugs = [...registryComponentSlugs].sort();

    expect(docsSlugs).toEqual(registrySlugs);
  });

  it("keeps docs scenarios scoped to known components", () => {
    const docsSlugSet = new Set(componentsList.map((component) => component.slug));

    for (const slug of Object.keys(docsScenarios)) {
      expect(docsSlugSet.has(slug)).toBe(true);
    }
  });

  it("generates docs config from registry docs metadata", () => {
    const registryDocsPath = path.resolve(process.cwd(), "../../registry/docs.json");

    expect(
      fs.existsSync(registryDocsPath),
      "missing registry docs source at registry/docs.json"
    ).toBe(true);

    const manifest = JSON.parse(
      fs.readFileSync(registryDocsPath, "utf-8")
    ) as RegistryDocsManifest;

    expect(manifest.components.map((component) => component.slug).sort()).toEqual(
      componentsList.map((component) => component.slug).sort()
    );

    const docsSlugsFromRegistry = manifest.components
      .filter((component) => component.docs)
      .map((component) => component.slug)
      .sort();

    expect(docsSlugsFromRegistry).toEqual(Object.keys(docsScenarios).sort());
  });

  it("has a demo entry for every component page path", () => {
    for (const component of componentsList) {
      if (component.variants?.length) {
        for (const variant of component.variants) {
          expect(componentDemos[variant.demoKey]).toBeDefined();
        }
        continue;
      }

      expect(componentDemos[component.slug]).toBeDefined();
    }
  });

  it("keeps generated demos config aligned with registry demos source", () => {
    const registryDemosPath = path.resolve(process.cwd(), "../../registry/demos.tsx");
    const generatedDemosPath = path.resolve(process.cwd(), "config/demos.tsx");

    expect(fs.existsSync(registryDemosPath), "missing registry demos source").toBe(true);
    expect(fs.existsSync(generatedDemosPath), "missing generated demos config").toBe(true);

    const normalizeGeneratedContent = (content: string) => {
      const lines = content.split("\n");
      const hasGeneratedBanner =
        lines.length >= 4 &&
        lines[0] === "// This file is auto-generated by `pnpm build:registry`." &&
        lines[1].startsWith("// Source of truth: `registry/docs.json") &&
        lines[2] === "// Do not edit this file manually." &&
        lines[3] === "";

      return (hasGeneratedBanner ? lines.slice(4).join("\n") : content).trimEnd();
    };

    expect(normalizeGeneratedContent(fs.readFileSync(generatedDemosPath, "utf-8"))).toBe(
      normalizeGeneratedContent(fs.readFileSync(registryDemosPath, "utf-8")),
    );
  });

  it("keeps docs ui component files mirrored from registry sources", () => {
    for (const slug of registryComponentSlugs) {
      const registryPath = path.resolve(process.cwd(), "../../registry", slug, "component.tsx");
      const docsPath = path.resolve(process.cwd(), "components/ui", `${slug}.tsx`);

      expect(fs.existsSync(registryPath), `missing registry source for ${slug}`).toBe(true);
      expect(fs.existsSync(docsPath), `missing docs ui file for ${slug}`).toBe(true);
      expect(fs.readFileSync(docsPath, "utf-8")).toBe(fs.readFileSync(registryPath, "utf-8"));
    }
  });

  it("keeps split registry artifacts aligned with the canonical registry sources", () => {
    const splitIndexPath = path.resolve(process.cwd(), "public/registry/index.json");
    const splitIndex = JSON.parse(fs.readFileSync(splitIndexPath, "utf-8")) as { components: string[] };

    expect([...splitIndex.components].sort()).toEqual([...registryComponentSlugs].sort());

    for (const slug of splitIndex.components) {
      const splitPayloadPath = path.resolve(process.cwd(), "public/registry", `${slug}.json`);
      const registrySourcePath = path.resolve(process.cwd(), "../../registry", slug, "component.tsx");

      expect(fs.existsSync(splitPayloadPath), `missing split registry payload for ${slug}`).toBe(true);

      const splitPayload = JSON.parse(fs.readFileSync(splitPayloadPath, "utf-8")) as {
        name: string;
        files: Array<{ path: string; content: string }>;
      };

      expect(splitPayload.name).toBe(slug);
      expect(splitPayload.files.some((file) => file.path === `${slug}/component.tsx`)).toBe(true);
      expect(
        splitPayload.files.find((file) => file.path === `${slug}/component.tsx`)?.content.trimEnd()
      ).toBe(fs.readFileSync(registrySourcePath, "utf-8").trimEnd());
    }
  });

  it("keeps shadcn-compatible /public/r registry aligned with registry slugs and split payloads", () => {
    const rDir = path.resolve(process.cwd(), "public/r");
    const manifestPath = path.join(rDir, "registry.json");

    expect(fs.existsSync(manifestPath), "missing public/r/registry.json (run pnpm build:registry)").toBe(
      true,
    );

    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8")) as {
      $schema: string;
      items: Array<{
        name: string;
        type: string;
        dependencies: string[];
        files: Array<{ path: string; type: string; target?: string; content?: string }>;
        tailwind?: { config: unknown };
      }>;
    };

    expect(manifest.$schema).toBe("https://ui.shadcn.com/schema/registry.json");
    expect(manifest.items.length).toBe(registryComponentSlugs.length);

    const manifestNames = manifest.items.map((i) => i.name).sort();
    expect(manifestNames).toEqual([...registryComponentSlugs].sort());

    for (const slug of registryComponentSlugs) {
      const itemPath = path.join(rDir, `${slug}.json`);
      expect(fs.existsSync(itemPath), `missing public/r/${slug}.json`).toBe(true);

      const fullItem = JSON.parse(fs.readFileSync(itemPath, "utf-8")) as {
        $schema: string;
        name: string;
        type: string;
        dependencies: string[];
        files: Array<{ path: string; content: string; type: string; target?: string }>;
        tailwind?: { config: unknown };
      };

      expect(fullItem.$schema).toBe("https://ui.shadcn.com/schema/registry-item.json");
      expect(fullItem.name).toBe(slug);
      expect(fullItem.type).toBe("registry:ui");
      expect(fullItem.files.length).toBeGreaterThan(0);

      const ui = fullItem.files[0];
      const expectedPath = `components/ui/${slug}.tsx`;
      expect(ui.path).toBe(expectedPath);
      expect(ui.target).toBe(expectedPath);
      expect(ui.type).toBe("registry:component");
      expect(ui.content.trim().length).toBeGreaterThan(0);

      const splitPayloadPath = path.resolve(process.cwd(), "public/registry", `${slug}.json`);
      const splitPayload = JSON.parse(fs.readFileSync(splitPayloadPath, "utf-8")) as {
        name: string;
        files: Array<{ path: string; content: string }>;
      };
      const splitUi = splitPayload.files.find((f) => f.path === `${slug}/component.tsx`);
      expect(splitUi, `split registry missing ${slug}/component.tsx`).toBeDefined();
      expect(ui.content.trimEnd()).toBe(splitUi!.content.trimEnd());

      const manifestRow = manifest.items.find((i) => i.name === slug);
      expect(manifestRow).toBeDefined();
      expect(manifestRow!.dependencies).toEqual(fullItem.dependencies);
      expect(manifestRow!.type).toBe("registry:ui");

      for (const f of manifestRow!.files) {
        expect("content" in f && f.content !== undefined).toBe(false);
      }

      const { content: _omit, ...fileMeta } = fullItem.files[0];
      expect(manifestRow!.files[0]).toEqual(fileMeta);

      if (fullItem.tailwind) {
        expect(manifestRow!.tailwind).toEqual(fullItem.tailwind);
      } else {
        expect(manifestRow!.tailwind).toBeUndefined();
      }
    }
  });
});
