import fs from "fs";
import path from "path";
import { describe, expect, it } from "vitest";
import { assembleDemosSource } from "./assemble-demos";

const ROOT = path.join(__dirname, "..");
const GENERATED_DEMOS = path.join(ROOT, "apps/www/config/demos.tsx");

function stripGeneratedBanner(content: string) {
  const lines = content.split("\n");
  const hasGeneratedBanner =
    lines.length >= 4 &&
    lines[0] === "// This file is auto-generated by `pnpm build:registry`." &&
    lines[1].startsWith("// Source of truth: `registry/components/*.json") &&
    lines[2] === "// Do not edit this file manually." &&
    lines[3] === "";

  return (hasGeneratedBanner ? lines.slice(4).join("\n") : content).trimEnd();
}

describe("assemble-demos", () => {
  it("matches generated apps/www/config/demos.tsx body", async () => {
    expect(fs.existsSync(GENERATED_DEMOS), "run pnpm build:registry first").toBe(true);

    const assembled = stripGeneratedBanner(await assembleDemosSource());
    const generated = stripGeneratedBanner(fs.readFileSync(GENERATED_DEMOS, "utf-8"));

    expect(assembled).toBe(generated);
  });

  it("includes every key listed in demo-key-order.json", async () => {
    const orderPath = path.join(ROOT, "registry/demos/demo-key-order.json");
    const keyOrder = JSON.parse(fs.readFileSync(orderPath, "utf-8")) as string[];
    const assembled = await assembleDemosSource();

    for (const key of keyOrder) {
      const quoted = `"${key}":`;
      const bare = `${key}:`;
      expect(assembled.includes(quoted) || assembled.includes(bare)).toBe(true);
    }
  });
});
