
import fs from "fs-extra";
import path from "path";
import { registry, type RegistryChangelogEntry } from "../registry/config";
// @ts-expect-error — .mjs module without ambient types
import { resolvePathUnderDir } from "./validate-registry.lib.mjs";

const REGISTRY_DIR = path.join(__dirname, "../registry");
const REGISTRY_DOCS_FILE = path.join(REGISTRY_DIR, "docs.json");
const REGISTRY_CHANGELOGS_FILE = path.join(REGISTRY_DIR, "changelogs.json");
const OUTPUT_FILE = path.join(__dirname, "../registry.json");
const APP_PUBLIC_DIR = path.join(__dirname, "../apps/www/public");
const APP_PUBLIC_OUTPUT_FILE = path.join(APP_PUBLIC_DIR, "registry.json");
const APP_PUBLIC_REGISTRY_DIR = path.join(APP_PUBLIC_DIR, "registry");
const APP_PUBLIC_SHADCN_DIR = path.join(APP_PUBLIC_DIR, "r");
const APP_COMPONENTS_UI_DIR = path.join(__dirname, "../apps/www/components/ui");
const APP_CONFIG_DIR = path.join(__dirname, "../apps/www/config");
const APP_COMPONENTS_CONFIG_FILE = path.join(APP_CONFIG_DIR, "components.ts");
const APP_DOCS_SCENARIOS_CONFIG_FILE = path.join(APP_CONFIG_DIR, "docs-scenarios.ts");
const APP_DEMOS_CONFIG_FILE = path.join(APP_CONFIG_DIR, "demos.tsx");

// Loose semver — full prerelease/build syntax not required for component versions.
const SEMVER_RE = /^\d+\.\d+\.\d+$/;
const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

type RegistryEntry = (typeof registry)[number] & {
  files: Array<{
    path: string;
    content: string;
    type: string;
  }>;
  meta: { version: string };
  changelog: RegistryChangelogEntry[];
};

type Changelogs = Record<string, RegistryChangelogEntry[]>;

type RegistryDocsVariant = {
  id: string;
  label: string;
  usageCode: string;
  demoKey: string;
  overflowVisible?: boolean;
};

type RegistryDocsScenario = {
  title: string;
  description: string;
  code: string;
  /**
   * Optional key into `componentDemos`. When set, the docs page renders a
   * live preview above the code block. Convention: `<slug>:<scenario-key>`,
   * with the corresponding entry registered in `registry/demos.tsx`.
   */
  demoKey?: string;
};

type RegistryDocsComponent = {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category?: string;
  /** "block" routes the entry under /blocks instead of /components. Omitted = component. */
  kind?: "block";
  /** ISO date (YYYY-MM-DD) — drives the "NEW" highlight for ~24h after add. */
  addedAt?: string;
  props: Array<{
    name: string;
    type: string;
    description: string;
    default?: string;
  }>;
  usageCode?: string;
  variants?: RegistryDocsVariant[];
  docs?: {
    overview: string;
    scenarios: RegistryDocsScenario[];
  };
};

type RegistryDocsManifest = {
  demos: {
    sourceFile: string;
  };
  components: RegistryDocsComponent[];
};

function renderGeneratedBanner(sourceFile: string) {
  return [
    "// This file is auto-generated by `pnpm build:registry`.",
    `// Source of truth: \`${sourceFile}\`.`,
    "// Do not edit this file manually.",
    "",
  ].join("\n");
}

function renderComponentsConfig(manifest: RegistryDocsManifest) {
  const iconNames = [...new Set(manifest.components.map((component) => component.icon))].sort();
  const componentDefinitions = manifest.components.map(({ docs: _docs, ...component }) => component);

  return `${renderGeneratedBanner("registry/docs.json")}import type { ElementType } from "react";
import {
${iconNames.map((iconName) => `  ${iconName},`).join("\n")}
} from "lucide-react";

export type ComponentVariant = {
  id: string;
  label: string;
  usageCode: string;
  demoKey: string;
  overflowVisible?: boolean;
};

export type ComponentItem = {
  slug: string;
  name: string;
  description: string;
  icon: ElementType;
  category?: string;
  /** "block" routes the entry under /blocks instead of /components. */
  kind?: "block";
  /** ISO date (YYYY-MM-DD) component was added. Drives the "NEW" highlight for ~24h. */
  addedAt?: string;
  props?: {
    name: string;
    type: string;
    default?: string;
    description: string;
  }[];
  usageCode?: string;
  variants?: ComponentVariant[];
};

type ComponentDefinition = Omit<ComponentItem, "icon"> & {
  icon: keyof typeof iconMap;
};

const iconMap = {
${iconNames.map((iconName) => `  ${iconName},`).join("\n")}
} satisfies Record<string, ElementType>;

const componentDefinitions = ${JSON.stringify(componentDefinitions, null, 2)} satisfies ComponentDefinition[];

export const componentsList: ComponentItem[] = componentDefinitions.map((component) => ({
  ...component,
  icon: iconMap[component.icon],
}));

/** Window during which a freshly added component is highlighted as NEW. */
export const NEW_COMPONENT_WINDOW_MS = 24 * 60 * 60 * 1000;

/**
 * Returns true if \`addedAt\` is within the last 24 hours.
 * Pure function so server and client agree without a hydration mismatch
 * — pass a stable \`now\` if you want deterministic SSR.
 */
export function isNewComponent(
  addedAt: string | undefined,
  now: number = Date.now(),
): boolean {
  if (!addedAt) return false;
  const t = Date.parse(addedAt);
  if (Number.isNaN(t)) return false;
  return now - t < NEW_COMPONENT_WINDOW_MS;
}
`;
}

function renderDocsScenariosConfig(manifest: RegistryDocsManifest) {
  const docsEntries = Object.fromEntries(
    manifest.components
      .filter((component) => component.docs)
      .map((component) => [
        component.slug,
        {
          slug: component.slug,
          overview: component.docs?.overview ?? "",
          scenarios: component.docs?.scenarios ?? [],
        },
      ]),
  );

  return `${renderGeneratedBanner("registry/docs.json")}export type DocScenario = {
  title: string;
  description: string;
  code: string;
  /** Optional key into \`componentDemos\` — when set, the docs page renders a live preview. */
  demoKey?: string;
};

export type ComponentDocs = {
  slug: string;
  overview: string;
  scenarios: DocScenario[];
};

export const docsScenarios: Record<string, ComponentDocs> = ${JSON.stringify(docsEntries, null, 2)};
`;
}

async function renderDemosConfig(manifest: RegistryDocsManifest) {
  const demosSourcePath = resolvePathUnderDir(
    path.join(__dirname, ".."),
    manifest.demos.sourceFile,
  );
  if (!(await fs.pathExists(demosSourcePath))) {
    throw new Error(`Missing demos source at ${demosSourcePath}`);
  }

  const demosSource = await fs.readFile(demosSourcePath, "utf-8");
  const generatedBanner = renderGeneratedBanner(
    `registry/docs.json -> ${manifest.demos.sourceFile}`,
  ).trimEnd();
  const bodyWithoutBanner = demosSource.replace(
    /^\/\/ This file is auto-generated by `pnpm build:registry`\.\n\/\/ Source of truth: `registry\/docs\.json`(?: -> [^`]+)?\.\n\/\/ Do not edit this file manually\.\n\n/,
    "",
  );

  return `${generatedBanner}\n\n${bodyWithoutBanner}`;
}

function compareSemver(a: string, b: string): number {
  const [aMaj, aMin, aPat] = a.split(".").map(Number);
  const [bMaj, bMin, bPat] = b.split(".").map(Number);
  if (aMaj !== bMaj) return aMaj - bMaj;
  if (aMin !== bMin) return aMin - bMin;
  return aPat - bPat;
}

// `loadChangelogs` mirrors the shape-level rules of the `Changelogs` zod
// schema in `scripts/validate-registry.lib.mjs`. Both must stay in sync:
// the build script is the fast-feedback path for contributors, the zod
// validator is the post-build CI gate. If you add a rule here, mirror it
// in the zod schema (and vice versa).
async function loadChangelogs(slugs: string[]): Promise<Changelogs> {
  if (!(await fs.pathExists(REGISTRY_CHANGELOGS_FILE))) {
    throw new Error(`Missing changelog source at ${REGISTRY_CHANGELOGS_FILE}`);
  }
  const raw = (await fs.readJson(REGISTRY_CHANGELOGS_FILE)) as unknown;
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("registry/changelogs.json must be an object keyed by slug");
  }
  const changelogs = raw as Record<string, unknown>;

  const errors: string[] = [];
  const out: Changelogs = {};

  for (const slug of slugs) {
    const entries = changelogs[slug];
    if (!Array.isArray(entries) || entries.length === 0) {
      errors.push(`changelogs.json: missing or empty entry for "${slug}"`);
      continue;
    }
    const normalized: RegistryChangelogEntry[] = [];
    for (const [i, entry] of entries.entries()) {
      const where = `${slug}[${i}]`;
      if (!entry || typeof entry !== "object") {
        errors.push(`changelogs.json: ${where} must be an object`);
        continue;
      }
      const e = entry as Record<string, unknown>;
      if (typeof e.version !== "string" || !SEMVER_RE.test(e.version)) {
        errors.push(`changelogs.json: ${where}.version must match \\d+.\\d+.\\d+ (got ${JSON.stringify(e.version)})`);
        continue;
      }
      if (typeof e.date !== "string" || !ISO_DATE_RE.test(e.date)) {
        errors.push(`changelogs.json: ${where}.date must be YYYY-MM-DD (got ${JSON.stringify(e.date)})`);
        continue;
      }
      if (
        !Array.isArray(e.changes) ||
        e.changes.length === 0 ||
        !e.changes.every((c) => typeof c === "string" && c.trim().length > 0)
      ) {
        errors.push(`changelogs.json: ${where}.changes must be a non-empty array of non-empty strings`);
        continue;
      }
      normalized.push({
        version: e.version,
        date: e.date,
        changes: e.changes as string[],
      });
    }
    // Enforce newest-first ordering: build script reads entries[0] as the
    // current meta.version, so an out-of-order array would silently demote.
    for (let i = 1; i < normalized.length; i++) {
      if (compareSemver(normalized[i - 1].version, normalized[i].version) <= 0) {
        errors.push(
          `changelogs.json: "${slug}" entries must be newest-first (descending semver); ` +
            `index ${i - 1} (${normalized[i - 1].version}) is not greater than index ${i} (${normalized[i].version})`,
        );
        break;
      }
    }
    out[slug] = normalized;
  }

  // Catch stray slugs in changelogs.json that don't exist in the registry.
  const slugSet = new Set(slugs);
  for (const key of Object.keys(changelogs)) {
    if (!slugSet.has(key)) {
      errors.push(`changelogs.json: stray entry "${key}" has no matching registry component`);
    }
  }

  if (errors.length > 0) {
    throw new Error(`Changelog validation failed:\n  - ${errors.join("\n  - ")}`);
  }

  return out;
}

async function loadRegistryDocsManifest(entries: RegistryEntry[]) {
  if (!(await fs.pathExists(REGISTRY_DOCS_FILE))) {
    throw new Error(`Missing docs metadata source at ${REGISTRY_DOCS_FILE}`);
  }

  const manifest = (await fs.readJson(REGISTRY_DOCS_FILE)) as RegistryDocsManifest;
  if (!manifest.demos?.sourceFile) {
    throw new Error("registry/docs.json must include demos.sourceFile");
  }
  const registrySlugs = entries.map((entry) => entry.name).sort();
  const docsSlugs = manifest.components.map((component) => component.slug).sort();

  if (JSON.stringify(registrySlugs) !== JSON.stringify(docsSlugs)) {
    throw new Error(
      [
        "Registry docs metadata is out of sync with registry/config.ts.",
        `registry/config.ts slugs: ${registrySlugs.join(", ")}`,
        `registry/docs.json slugs: ${docsSlugs.join(", ")}`,
      ].join("\n"),
    );
  }

  return manifest;
}

async function syncDocsRegistryArtifacts(entries: RegistryEntry[], changelogs: Changelogs) {
  await fs.outputJson(APP_PUBLIC_OUTPUT_FILE, entries, { spaces: 2 });
  await fs.emptyDir(APP_PUBLIC_REGISTRY_DIR);
  await fs.outputJson(
    path.join(APP_PUBLIC_REGISTRY_DIR, "index.json"),
    { components: entries.map((entry) => entry.name) },
    { spaces: 2 },
  );

  await Promise.all(
    entries.map((entry) =>
      fs.outputJson(path.join(APP_PUBLIC_REGISTRY_DIR, `${entry.name}.json`), entry, { spaces: 2 }),
    ),
  );

  // Publish the aggregate changelog so future `uniqueui update`/`diff` can
  // resolve per-slug history with a single fetch.
  await fs.outputJson(
    path.join(APP_PUBLIC_REGISTRY_DIR, "changelogs.json"),
    changelogs,
    { spaces: 2 },
  );
}

async function syncDocsUiComponents(entries: RegistryEntry[]) {
  await fs.ensureDir(APP_COMPONENTS_UI_DIR);
  const expectedFiles = new Set(entries.map((entry) => `${entry.name}.tsx`));
  const existingFiles = await fs.readdir(APP_COMPONENTS_UI_DIR);

  await Promise.all(
    existingFiles
      .filter((fileName) => fileName.endsWith(".tsx") && !expectedFiles.has(fileName))
      .map((fileName) => fs.remove(path.join(APP_COMPONENTS_UI_DIR, fileName))),
  );

  await Promise.all(
    entries.map(async (entry) => {
      const componentFile = entry.files.find((file) => file.type === "registry:ui");
      if (!componentFile || typeof componentFile.content !== "string") {
        return;
      }

      await fs.writeFile(path.join(APP_COMPONENTS_UI_DIR, `${entry.name}.tsx`), componentFile.content);
    }),
  );
}

async function syncDocsConfig(manifest: RegistryDocsManifest) {
  await fs.ensureDir(APP_CONFIG_DIR);
  await fs.writeFile(APP_COMPONENTS_CONFIG_FILE, renderComponentsConfig(manifest));
  await fs.writeFile(APP_DOCS_SCENARIOS_CONFIG_FILE, renderDocsScenariosConfig(manifest));
  await fs.writeFile(APP_DEMOS_CONFIG_FILE, await renderDemosConfig(manifest));
}

async function syncShadcnRegistry(entries: RegistryEntry[], manifest: RegistryDocsManifest) {
  // Validate all entries before clearing the directory to avoid partial state on failure.
  for (const entry of entries) {
    if (!entry.files.some((f) => f.type === "registry:ui")) {
      throw new Error(
        `syncShadcnRegistry: component "${entry.name}" has no registry:ui file; cannot emit shadcn registry item.`,
      );
    }
  }

  await fs.emptyDir(APP_PUBLIC_SHADCN_DIR);

  // Build a lookup map from slug → docs metadata
  const docsBySlug = new Map(manifest.components.map((c) => [c.slug, c]));

  // Use Promise.all over entries.map (not concurrent push) so manifest item order matches registry/config.ts.
  const shadcnItems = await Promise.all(
    entries.map(async (entry) => {
      const doc = docsBySlug.get(entry.name);

      // Map each file to the shadcn registry-item format.
      // - registry:ui  → registry:component, installed at components/ui/{slug}.tsx
      // - registry:util → omitted (shadcn projects already have @/lib/utils from `shadcn init`)
      const installPath = `components/ui/${entry.name}.tsx`;
      const shadcnFiles = entry.files
        .filter((f) => f.type === "registry:ui")
        .map((f) => ({
          path: installPath,
          content: f.content,
          type: "registry:component" as const,
          target: installPath,
        }));

      const item: Record<string, unknown> = {
        $schema: "https://ui.shadcn.com/schema/registry-item.json",
        name: entry.name,
        type: "registry:ui",
        ...(doc?.name ? { title: doc.name } : {}),
        ...(doc?.description ? { description: doc.description } : {}),
        dependencies: entry.dependencies,
        files: shadcnFiles,
      };

      // Map tailwindConfig → tailwind.config (shadcn schema key)
      if (entry.tailwindConfig) {
        item.tailwind = { config: entry.tailwindConfig };
      }

      await fs.outputJson(path.join(APP_PUBLIC_SHADCN_DIR, `${entry.name}.json`), item, { spaces: 2 });

      return {
        name: entry.name,
        type: "registry:ui",
        ...(doc?.name ? { title: doc.name } : {}),
        ...(doc?.description ? { description: doc.description } : {}),
        dependencies: entry.dependencies,
        files: shadcnFiles.map(({ content: _content, ...rest }) => rest),
        ...(entry.tailwindConfig ? { tailwind: { config: entry.tailwindConfig } } : {}),
      };
    }),
  );

  await fs.outputJson(
    path.join(APP_PUBLIC_SHADCN_DIR, "registry.json"),
    {
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: "uniqueui",
      homepage: "https://uniqueui-platform.vercel.app",
      items: shadcnItems,
    },
    { spaces: 2 },
  );
}

async function buildRegistry() {
  console.log("Building registry...");

  const slugs = registry.map((entry) => entry.name);
  const changelogs = await loadChangelogs(slugs);

  const result: RegistryEntry[] = [];

  for (const component of registry) {
    const componentFiles = [];

    for (const file of component.files) {
      if (file.content) {
        componentFiles.push({
          path: file.path,
          content: file.content,
          type: file.type,
        });
        continue;
      }

      const filePath = resolvePathUnderDir(REGISTRY_DIR, file.path);
      try {
        const content = await fs.readFile(filePath, "utf-8");
        componentFiles.push({
          path: file.path,
          content,
          type: file.type,
        });
      } catch (error) {
        console.error(`Error reading file ${file.path} for component ${component.name}:`, error);
        process.exit(1);
      }
    }

    const entryChangelog = changelogs[component.name];
    // Latest entry is first in changelog (newest at top, like a release-notes file).
    const latest = entryChangelog[0];
    result.push({
      ...component,
      files: componentFiles,
      meta: { version: latest.version },
      changelog: entryChangelog,
    });
  }

  const docsManifest = await loadRegistryDocsManifest(result);

  await fs.outputJson(OUTPUT_FILE, result, { spaces: 2 });
  await syncDocsRegistryArtifacts(result, changelogs);
  await syncDocsUiComponents(result);
  await syncDocsConfig(docsManifest);
  await syncShadcnRegistry(result, docsManifest);
  console.log(`Registry built successfully: ${OUTPUT_FILE}`);
  console.log(`Registry synced to docs public root: ${APP_PUBLIC_OUTPUT_FILE}`);
  console.log(`Registry synced to docs public directory: ${APP_PUBLIC_REGISTRY_DIR}`);
  console.log(`Registry synced to docs ui components: ${APP_COMPONENTS_UI_DIR}`);
  console.log(`Docs config generated from registry source: ${REGISTRY_DOCS_FILE}`);
  console.log(`shadcn-compatible registry synced to: ${APP_PUBLIC_SHADCN_DIR}`);
}

buildRegistry().catch((err) => {
  console.error(err);
  process.exit(1);
});
