/**
 * Shared parser for registry demo fragment `export const demoEntries = { ... }` bodies.
 * Keep split-demos.mjs logic in sync when changing comma/depth rules.
 */

export function stripLeadingComments(entry: string): string {
  return entry.replace(/^(?:\s*\/\/[^\n]*\n)+/, "");
}

export function parseEntryKey(entry: string): string {
  const stripped = stripLeadingComments(entry).trimStart();
  const quoted = stripped.match(/^"([^"]+)":/);
  if (quoted) return quoted[1];
  const bare = stripped.match(/^([A-Za-z0-9_-]+):/);
  if (bare) return bare[1];
  throw new Error(`Could not parse demo key from: ${stripped.slice(0, 80)}`);
}

export function extractDemoEntriesBody(source: string): string {
  const marker = "export const demoEntries";
  const start = source.indexOf(marker);
  if (start === -1) {
    throw new Error("demo fragment missing `export const demoEntries`");
  }

  const braceStart = source.indexOf("{", start);
  let depth = 0;
  let inString: string | null = null;
  let escape = false;
  let inLineComment = false;
  let inBlockComment = false;

  for (let i = braceStart; i < source.length; i++) {
    const c = source[i];
    const next = source[i + 1];

    if (inLineComment) {
      if (c === "\n") inLineComment = false;
      continue;
    }
    if (inBlockComment) {
      if (c === "*" && next === "/") {
        inBlockComment = false;
        i++;
      }
      continue;
    }
    if (inString) {
      if (escape) {
        escape = false;
        continue;
      }
      if (c === "\\") {
        escape = true;
        continue;
      }
      if (c === inString) inString = null;
      continue;
    }

    if (c === "/" && next === "/") {
      inLineComment = true;
      i++;
      continue;
    }
    if (c === "/" && next === "*") {
      inBlockComment = true;
      i++;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") {
      inString = c;
      continue;
    }
    if (c === "{") depth++;
    if (c === "}") {
      depth--;
      if (depth === 0) {
        return source.slice(braceStart + 1, i);
      }
    }
  }

  throw new Error("Unbalanced braces in demoEntries");
}

export function splitTopLevelEntries(objectBody: string): Map<string, string> {
  const map = new Map<string, string>();
  let braceDepth = 0;
  let parenDepth = 0;
  let bracketDepth = 0;
  let entryStart = 0;
  let inString: string | null = null;
  let escape = false;
  let inLineComment = false;
  let inBlockComment = false;

  for (let i = 0; i <= objectBody.length; i++) {
    const c = objectBody[i];
    const next = objectBody[i + 1];

    if (i === objectBody.length) {
      const tail = objectBody.slice(entryStart).replace(/,\s*$/, "");
      if (tail) {
        const key = parseEntryKey(tail);
        map.set(key, tail);
      }
      break;
    }

    if (inLineComment) {
      if (c === "\n") inLineComment = false;
      continue;
    }
    if (inBlockComment) {
      if (c === "*" && next === "/") {
        inBlockComment = false;
        i++;
      }
      continue;
    }
    if (inString) {
      if (escape) {
        escape = false;
        continue;
      }
      if (c === "\\") {
        escape = true;
        continue;
      }
      if (c === inString) inString = null;
      continue;
    }

    if (c === "/" && next === "/") {
      inLineComment = true;
      i++;
      continue;
    }
    if (c === "/" && next === "*") {
      inBlockComment = true;
      i++;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") {
      inString = c;
      continue;
    }
    if (c === "{") braceDepth++;
    if (c === "}") braceDepth--;
    if (c === "(") parenDepth++;
    if (c === ")") parenDepth--;
    if (c === "[") bracketDepth++;
    if (c === "]") bracketDepth--;
    if (
      c === "," &&
      braceDepth === 0 &&
      parenDepth === 0 &&
      bracketDepth === 0
    ) {
      const chunk = objectBody.slice(entryStart, i).replace(/,\s*$/, "");
      if (chunk) {
        const key = parseEntryKey(chunk);
        map.set(key, chunk);
      }
      entryStart = i + 1;
    }
  }

  return map;
}

export function stripGeneratedDemosBanner(content: string): string {
  const lines = content.split("\n");
  const hasGeneratedBanner =
    lines.length >= 4 &&
    lines[0] === "// This file is auto-generated by `pnpm build:registry`." &&
    lines[1].startsWith("// Source of truth: `registry/components/*.json") &&
    lines[2] === "// Do not edit this file manually." &&
    lines[3] === "";

  return (hasGeneratedBanner ? lines.slice(4).join("\n") : content).trimEnd();
}

export function parseDemoKeyOrder(raw: unknown): string[] {
  if (!Array.isArray(raw) || raw.some((key) => typeof key !== "string")) {
    throw new Error("demo-key-order.json must be a JSON array of strings");
  }

  const keyOrder = raw as string[];
  const seen = new Set<string>();
  const duplicates: string[] = [];
  for (const key of keyOrder) {
    if (seen.has(key)) duplicates.push(key);
    seen.add(key);
  }
  if (duplicates.length > 0) {
    throw new Error(
      `demo-key-order.json contains duplicate keys: ${[...new Set(duplicates)].join(", ")}`,
    );
  }

  return keyOrder;
}
