import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const rootDir = process.cwd();
const cliPackagePath = path.join(rootDir, "packages/cli/package.json");
const versionFilePath = path.join(rootDir, "apps/www/config/version.ts");

async function syncVersion() {
  const pkg = JSON.parse(await readFile(cliPackagePath, "utf8"));
  if (typeof pkg.version !== "string" || pkg.version.length === 0) {
    throw new Error(`sync-version: missing "version" in ${cliPackagePath}`);
  }

  const contents =
    `// AUTO-GENERATED by scripts/build-registry.ts — do not edit by hand.\n` +
    `// Mirrors the published CLI version in packages/cli/package.json.\n` +
    `export const LIBRARY_VERSION = "${pkg.version}";\n`;

  await mkdir(path.dirname(versionFilePath), { recursive: true });
  await writeFile(versionFilePath, contents, "utf8");
  console.log(`Synced library version (${pkg.version}) to ${versionFilePath}`);
}

await syncVersion();
