import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

async function run() {
    const ROOT_DIR = path.join(__dirname, '..');
    const COMPONENTS_FILE = path.join(ROOT_DIR, 'apps/www/config/components.ts');

    // 1. Extract slugs and usage codes from the config file
    console.log('Extracting component configurations...');
    const content = fs.readFileSync(COMPONENTS_FILE, 'utf-8');

    const components: { slug: string, usageCode: string }[] = [];
    const slugRegex = /slug:\s*"([^"]+)"/g;
    let match;

    /**
     * Extract the content of a backtick-delimited template literal from `content`
     * starting at position `startTick` (the opening backtick).
     * Correctly handles:
     *   - escaped backticks: \`
     *   - nested ${...} expressions (which can contain more backticks)
     * Returns the raw inner content and the index of the closing backtick.
     */
    function extractTemplateLiteral(src: string, startTick: number): { raw: string; end: number } {
        let i = startTick + 1;
        let depth = 0; // tracks ${...} depth
        while (i < src.length) {
            const ch = src[i];
            if (ch === '\\') {
                i += 2; // skip escaped character (e.g. \` or \$)
                continue;
            }
            if (depth === 0 && ch === '`') {
                // Found closing backtick outside of any expression
                return { raw: src.substring(startTick + 1, i), end: i };
            }
            if (ch === '$' && src[i + 1] === '{') {
                depth++;
                i += 2;
                continue;
            }
            if (ch === '}' && depth > 0) {
                depth--;
                i++;
                continue;
            }
            i++;
        }
        return { raw: src.substring(startTick + 1, i), end: i };
    }

    while ((match = slugRegex.exec(content)) !== null) {
        const slug = match[1];
        const usageIdx = content.indexOf('usageCode:', match.index);

        if (usageIdx !== -1) {
            const startTick = content.indexOf('`', usageIdx);
            if (startTick === -1) continue;

            const { raw, end } = extractTemplateLiteral(content, startTick);
            // Unescape what was escaped in the source file
            const usageCode = raw
                .replace(/\\`/g, '`')
                .replace(/\\\$/g, '$');

            components.push({ slug, usageCode });
        }
    }

    console.log(`Found ${components.length} components to test.`);

    const TEST_DIR = path.join(ROOT_DIR, 'e2e-components-test');

    if (fs.existsSync(TEST_DIR)) {
        fs.rmSync(TEST_DIR, { recursive: true, force: true });
    }

    // 2. Create a fresh Next.js project
    console.log('\n--- Creating fresh Next.js app ---');
    try {
        const out1 = execSync(`echo "\\n" | npx create-next-app@14 e2e-components-test --typescript --tailwind --eslint --app --src-dir --import-alias "@/*" --use-npm --yes`, {
            cwd: ROOT_DIR
        });
        console.log(out1.toString());
    } catch (e: any) { console.error(e.stdout?.toString()); console.error(e.stderr?.toString()); process.exit(1); }

    // 3. Initialize the UniqueUI CLI manually (bypassing interactive init prompts)
    console.log('\n--- Initializing UniqueUI CLI ---');
    const configData = {
        $schema: "https://uniqueui.com/schema.json",
        style: "default",
        rsc: true,
        tsx: true,
        tailwind: {
            config: "tailwind.config.ts",
            css: "app/globals.css",
            baseColor: "slate",
            cssVariables: true,
        },
        aliases: {
            components: "@/components",
            utils: "@/utils",
        },
        paths: {
            components: "src/components/ui",
            lib: "src/utils"
        }
    };
    fs.writeFileSync(path.join(TEST_DIR, 'components.json'), JSON.stringify(configData, null, 2));

    // Create utils/cn.ts
    const utilsDir = path.join(TEST_DIR, 'src/utils'); // Next.js creates src/ since we used --src-dir
    const cnContent = `import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}`;
    if (!fs.existsSync(utilsDir)) fs.mkdirSync(utilsDir, { recursive: true });
    fs.writeFileSync(path.join(utilsDir, 'cn.ts'), cnContent);

    // Also create src/lib/utils.ts — all components import `cn` from "@/lib/utils"
    const libDir = path.join(TEST_DIR, 'src/lib');
    if (!fs.existsSync(libDir)) fs.mkdirSync(libDir, { recursive: true });
    fs.writeFileSync(path.join(libDir, 'utils.ts'), cnContent);

    // Overwrite next.config to disable ESLint during builds — support both .ts and .mjs generated by create-next-app
    const nextConfigContent = `/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  eslint: { ignoreDuringBuilds: true },\n  typescript: { ignoreBuildErrors: false },\n};\nmodule.exports = nextConfig;\n`;
    // next 14 via create-next-app --typescript generates next.config.ts; older gen → next.config.mjs
    // We write next.config.js which takes precedence over both
    fs.writeFileSync(path.join(TEST_DIR, 'next.config.js'), nextConfigContent);
    // Also delete the generated next.config.ts / next.config.mjs so there's no conflict
    for (const configName of ['next.config.ts', 'next.config.mjs']) {
        const configPath = path.join(TEST_DIR, configName);
        if (fs.existsSync(configPath)) fs.unlinkSync(configPath);
    }
    console.log('Created components.json, src/utils/cn.ts, src/lib/utils.ts, and next.config.js manually.');

    // Install lucide-react so any component that imports icons compiles cleanly
    try {
        execSync('npm install lucide-react --save', { cwd: TEST_DIR });
        console.log('Installed lucide-react');
    } catch (e: any) { console.error('lucide-react install failed:', e.stdout?.toString()); }

    // 4. Loop through and add every component
    console.log('\n--- Adding Components ---');
    for (const comp of components) {
        console.log(`\nAdding: ${comp.slug}`);
        try {
            const out2 = execSync(`npx ts-node ../packages/cli/src/index.ts add ${comp.slug} --url ../registry.json`, {
                cwd: TEST_DIR
            });
            console.log(out2.toString());
        } catch (e: any) { console.error('Add failed:', e.stdout?.toString(), e.stderr?.toString()); }

        // 5. Inject the usage code as a page
        const pageDir = path.join(TEST_DIR, 'src/app', comp.slug);
        fs.mkdirSync(pageDir, { recursive: true });

        // Some usage blocks might need 'use client' if they use hooks. Let's ensure it's there.
        let finalCode = comp.usageCode;
        if (!finalCode.includes('"use client"') && !finalCode.includes("'use client'")) {
            finalCode = '"use client";\n\n' + finalCode;
        }

        fs.writeFileSync(path.join(pageDir, 'page.tsx'), finalCode);
    }

    // 6. Generate an index page to easily browse components
    console.log('\n--- Generating Index Page ---');
    const links = components.map(c =>
        `        <a href="/${c.slug}" className="p-4 border rounded-lg hover:bg-slate-100 transition-colors font-medium block text-center">\n          ${c.slug}\n        </a>`
    ).join('\n');

    const indexCode = `export default function Home() {
  return (
    <main className="min-h-screen p-10 max-w-5xl mx-auto font-sans">
      <h1 className="text-3xl font-bold mb-8 text-center">UniqueUI Sandbox</h1>
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
${links}
      </div>
    </main>
  );
}`;
    fs.writeFileSync(path.join(TEST_DIR, 'src/app/page.tsx'), indexCode);

    // 7. Verifying Project Compilation
    console.log('\n--- Verifying Project Compilation ---');
    try {
        const out3 = execSync(`CI=1 NEXT_TELEMETRY_DISABLED=1 npm run build`, { cwd: TEST_DIR });
        console.log(out3.toString());
        console.log('\n✅ E2E Component Installation Test Passed Successfully!');
        console.log('You can inspect the generated app at: ./e2e-components-test');
        // Optional Cleanup
        // fs.rmSync(TEST_DIR, { recursive: true, force: true });
    } catch (e: any) {
        console.error('\n❌ E2E Component Installation Test Failed during Build phase.');
        console.error(e.stdout?.toString()); console.error(e.stderr?.toString());
        process.exit(1);
    }
}

run().catch(console.error);
