// This file is auto-generated by `pnpm build:registry`.
// Source of truth: `registry/docs.json`.
// Do not edit this file manually.
export type DocScenario = {
  title: string;
  description: string;
  code: string;
};

export type ComponentDocs = {
  slug: string;
  overview: string;
  scenarios: DocScenario[];
};

export const docsScenarios: Record<string, ComponentDocs> = {
  "moving-border": {
    "slug": "moving-border",
    "overview": "MovingBorder traces an animated SVG path around a button or card, creating the appearance of a glowing line orbiting the element. The path speed and glow intensity are fully configurable.",
    "scenarios": [
      {
        "title": "Highlighted CTA button",
        "description": "Draw immediate attention to a primary action with an orbiting glow border.",
        "code": "import { MovingBorder } from \"@/components/ui/moving-border\";\n\nexport default function GlowCTA() {\n  return (\n    <MovingBorder duration={3000} borderRadius=\"9999px\">\n      <button className=\"px-8 py-3 font-semibold text-white bg-neutral-950 rounded-full\">\n        Start building for free\n      </button>\n    </MovingBorder>\n  );\n}"
      },
      {
        "title": "Featured pricing card",
        "description": "Indicate the recommended pricing tier with a subtle moving border that stands out from static cards.",
        "code": "import { MovingBorder } from \"@/components/ui/moving-border\";\n\nexport default function FeaturedPricingCard() {\n  return (\n    <MovingBorder duration={4000} borderRadius=\"1rem\" borderClassName=\"bg-[radial-gradient(var(--tw-gradient-stops))] from-purple-500 via-transparent to-transparent\">\n      <div className=\"p-8 bg-neutral-950 rounded-2xl min-w-[280px] space-y-4\">\n        <span className=\"text-xs font-bold uppercase tracking-widest text-purple-400\">\n          Most popular\n        </span>\n        <p className=\"text-4xl font-bold text-white\">\n          $29<span className=\"text-lg text-neutral-400\">/mo</span>\n        </p>\n        <button className=\"w-full py-3 bg-purple-600 text-white rounded-xl font-medium\">\n          Get started\n        </button>\n      </div>\n    </MovingBorder>\n  );\n}"
      }
    ]
  },
  "typewriter-text": {
    "slug": "typewriter-text",
    "overview": "TypewriterText cycles through an array of words with a smooth typing and erasing animation. It's great for hero headings that need to convey multiple value propositions without cluttering the layout.",
    "scenarios": [
      {
        "title": "Hero headline rotator",
        "description": "Swap your hero subtitle or adjective with a typewriter that cycles through your key benefits.",
        "code": "import { TypewriterText } from \"@/components/ui/typewriter-text\";\n\nexport default function HeroHeadline() {\n  return (\n    <h1 className=\"text-5xl font-bold text-white\">\n      Build{\" \"}\n      <TypewriterText\n        words={[\"faster\", \"smarter\", \"beautifully\"]}\n        className=\"text-purple-400\"\n      />\n      <br />\n      with UniqueUI\n    </h1>\n  );\n}"
      },
      {
        "title": "Loading / processing indicator",
        "description": "Use a single looping word to hint that background work is in progress.",
        "code": "import { TypewriterText } from \"@/components/ui/typewriter-text\";\n\nexport default function ProcessingBadge() {\n  return (\n    <div className=\"flex items-center gap-2 text-sm text-neutral-400\">\n      <span className=\"h-2 w-2 rounded-full bg-green-500 animate-pulse\" />\n      <TypewriterText\n        words={[\"Analyzing…\", \"Optimizing…\", \"Almost done…\"]}\n        typingSpeed={60}\n        deletingSpeed={40}\n        pauseDuration={1200}\n      />\n    </div>\n  );\n}"
      },
      {
        "title": "Feature tagline in a navbar",
        "description": "Animate a short tagline beside your logo to keep visitors engaged right from the header.",
        "code": "import { TypewriterText } from \"@/components/ui/typewriter-text\";\n\nexport default function NavTagline() {\n  return (\n    <nav className=\"flex items-center gap-3 px-6 py-4 border-b border-neutral-800\">\n      <span className=\"font-bold text-white\">UniqueUI</span>\n      <span className=\"text-neutral-600\">·</span>\n      <TypewriterText\n        words={[\"Copy-paste components\", \"Zero design system lock-in\", \"Motion-first\"]}\n        className=\"text-xs text-neutral-400 font-mono\"\n        typingSpeed={55}\n      />\n    </nav>\n  );\n}"
      }
    ]
  },
  "spotlight-card": {
    "slug": "spotlight-card",
    "overview": "SpotlightCard tracks your cursor and projects a soft radial light on the card surface, creating a sense of physical depth. Ideal anywhere you need premium-feeling content cards.",
    "scenarios": [
      {
        "title": "Pricing tier card",
        "description": "Make pricing options feel tactile and premium — spotlight highlights the selected plan naturally.",
        "code": "import { SpotlightCard } from \"@/components/ui/spotlight-card\";\n\nexport default function PricingCard() {\n  return (\n    <SpotlightCard theme=\"dark\" className=\"p-8 max-w-sm\">\n      <div className=\"space-y-4\">\n        <span className=\"text-xs font-semibold text-purple-400 uppercase tracking-widest\">\n          Pro\n        </span>\n        <p className=\"text-4xl font-bold text-white\">\n          $29<span className=\"text-lg text-neutral-400\">/mo</span>\n        </p>\n        <ul className=\"space-y-2 text-sm text-neutral-300\">\n          <li>✓ Unlimited components</li>\n          <li>✓ Commercial license</li>\n          <li>✓ Priority support</li>\n        </ul>\n        <button className=\"w-full py-3 bg-purple-600 hover:bg-purple-500 rounded-xl text-white font-semibold transition-colors\">\n          Get started\n        </button>\n      </div>\n    </SpotlightCard>\n  );\n}"
      },
      {
        "title": "Team member profile card",
        "description": "Spotlight turns a standard team grid into an interactive, warm experience.",
        "code": "import { SpotlightCard } from \"@/components/ui/spotlight-card\";\n\nexport default function TeamMemberCard() {\n  return (\n    <SpotlightCard theme=\"dark\" className=\"p-6 text-center\">\n      <img\n        src=\"/avatar.jpg\"\n        alt=\"Prashant\"\n        className=\"w-16 h-16 rounded-full mx-auto mb-4 object-cover\"\n      />\n      <h3 className=\"text-white font-semibold text-lg\">Prashant Kumar</h3>\n      <p className=\"text-neutral-400 text-sm\">Founder · Full-stack engineer</p>\n      <div className=\"mt-4 flex justify-center gap-3\">\n        <a href=\"#\" className=\"text-xs text-purple-400 hover:underline\">GitHub</a>\n        <a href=\"#\" className=\"text-xs text-purple-400 hover:underline\">Twitter</a>\n      </div>\n    </SpotlightCard>\n  );\n}"
      },
      {
        "title": "Feature highlight card",
        "description": "Wrap each feature description in a spotlight card to make your feature grid feel alive.",
        "code": "import { SpotlightCard } from \"@/components/ui/spotlight-card\";\nimport { Zap } from \"lucide-react\";\n\nexport default function FeatureCard() {\n  return (\n    <SpotlightCard theme=\"dark\" className=\"p-6\">\n      <div className=\"p-2.5 w-fit rounded-lg bg-purple-500/10 border border-purple-500/20 mb-4\">\n        <Zap className=\"w-5 h-5 text-purple-400\" />\n      </div>\n      <h3 className=\"text-white font-semibold mb-2\">Instant installs</h3>\n      <p className=\"text-neutral-400 text-sm leading-relaxed\">\n        One CLI command drops a single-file component into your project.\n        No dependency hell, no config files.\n      </p>\n    </SpotlightCard>\n  );\n}"
      }
    ]
  },
  "aurora-background": {
    "slug": "aurora-background",
    "overview": "AuroraBackground renders a shifting, color-cycling radial gradient behind your content. It uses a CSS keyframe animation that's optimized for performance and respects prefers-reduced-motion.",
    "scenarios": [
      {
        "title": "Full-page hero section",
        "description": "Wrap your entire landing hero with the aurora to create an immediate cinematic impression.",
        "code": "import { AuroraBackground } from \"@/components/ui/aurora-background\";\n\nexport default function HeroSection() {\n  return (\n    <AuroraBackground className=\"min-h-screen flex items-center justify-center\">\n      <div className=\"text-center space-y-4 z-10 relative\">\n        <h1 className=\"text-6xl font-bold text-white\">\n          Ship beautiful UIs\n        </h1>\n        <p className=\"text-neutral-300 text-xl max-w-xl mx-auto\">\n          Animated components that make your product feel alive.\n        </p>\n        <button className=\"mt-6 px-8 py-3 bg-white text-black rounded-full font-semibold\">\n          Get started\n        </button>\n      </div>\n    </AuroraBackground>\n  );\n}"
      },
      {
        "title": "Feature section banner",
        "description": "Apply the aurora to a single section mid-page to break up a long-scrolling layout.",
        "code": "import { AuroraBackground } from \"@/components/ui/aurora-background\";\n\nexport default function FeatureBanner() {\n  return (\n    <AuroraBackground\n      className=\"rounded-3xl overflow-hidden py-24 px-8 text-center\"\n      showRadialGradient={false}\n    >\n      <span className=\"text-xs uppercase tracking-widest text-purple-300 font-semibold\">\n        New in v2\n      </span>\n      <h2 className=\"mt-3 text-4xl font-bold text-white\">\n        Bento Grid layouts\n      </h2>\n      <p className=\"mt-2 text-neutral-400 max-w-md mx-auto\">\n        Drag-and-drop grid sections that adapt to any content type.\n      </p>\n    </AuroraBackground>\n  );\n}"
      },
      {
        "title": "CTA section with custom colors",
        "description": "Customize the aurora colors to match your brand palette on a bottom-of-page conversion section.",
        "code": "import { AuroraBackground } from \"@/components/ui/aurora-background\";\n\nexport default function CTASection() {\n  return (\n    <AuroraBackground\n      className=\"py-32 text-center\"\n      colors={[\"#7c3aed\", \"#2563eb\", \"#7c3aed\"]}\n    >\n      <div className=\"relative z-10 space-y-6\">\n        <h2 className=\"text-5xl font-bold text-white\">\n          Ready to build something great?\n        </h2>\n        <div className=\"flex gap-4 justify-center\">\n          <button className=\"px-6 py-3 bg-white text-neutral-900 rounded-full font-semibold\">\n            Start free\n          </button>\n          <button className=\"px-6 py-3 border border-white/30 text-white rounded-full\">\n            View docs\n          </button>\n        </div>\n      </div>\n    </AuroraBackground>\n  );\n}"
      }
    ]
  },
  "animated-tabs": {
    "slug": "animated-tabs",
    "overview": "AnimatedTabs uses a layoutId-driven underline or pill indicator to transition between tabs with a fluid spring. The active indicator follows the selected tab without a hard jump.",
    "scenarios": [
      {
        "title": "Settings panel",
        "description": "A classic tab bar for separating profile, notifications, and security settings.",
        "code": "import { AnimatedTabs } from \"@/components/ui/animated-tabs\";\n\nconst tabs = [\n  { id: \"profile\", label: \"Profile\" },\n  { id: \"notifications\", label: \"Notifications\" },\n  { id: \"security\", label: \"Security\" },\n];\n\nexport default function SettingsPanel() {\n  return (\n    <div className=\"max-w-2xl space-y-6\">\n      <AnimatedTabs tabs={tabs} defaultTab=\"profile\" />\n      {/* Render panel content based on active tab */}\n    </div>\n  );\n}"
      },
      {
        "title": "Dashboard content switcher",
        "description": "Switch between weekly, monthly, and yearly data views in a dashboard.",
        "code": "import { AnimatedTabs } from \"@/components/ui/animated-tabs\";\nimport { useState } from \"react\";\n\nconst ranges = [\n  { id: \"7d\", label: \"7 days\" },\n  { id: \"30d\", label: \"30 days\" },\n  { id: \"90d\", label: \"90 days\" },\n  { id: \"1y\", label: \"1 year\" },\n];\n\nexport default function DateRangeTabs() {\n  const [range, setRange] = useState(\"30d\");\n\n  return (\n    <div>\n      <AnimatedTabs\n        tabs={ranges}\n        defaultTab=\"30d\"\n        onChange={setRange}\n        size=\"sm\"\n      />\n      <p className=\"mt-4 text-sm text-neutral-400\">\n        Showing data for: {range}\n      </p>\n    </div>\n  );\n}"
      },
      {
        "title": "Product feature showcase tabs",
        "description": "Let marketing highlight different product features with animated tab transitions.",
        "code": "import { AnimatedTabs } from \"@/components/ui/animated-tabs\";\nimport { useState } from \"react\";\nimport { motion, AnimatePresence } from \"motion/react\";\n\nconst features = [\n  { id: \"speed\", label: \"Speed\", content: \"Deploy components in seconds with the CLI.\" },\n  { id: \"design\", label: \"Design\", content: \"Motion-first animations out of the box.\" },\n  { id: \"dx\", label: \"DX\", content: \"Single-file components, zero config.\" },\n];\n\nexport default function FeatureTabs() {\n  const [active, setActive] = useState(\"speed\");\n  const feature = features.find(f => f.id === active)!;\n\n  return (\n    <div className=\"space-y-6 max-w-lg\">\n      <AnimatedTabs tabs={features} defaultTab=\"speed\" onChange={setActive} />\n      <AnimatePresence mode=\"wait\">\n        <motion.p\n          key={active}\n          initial={{ opacity: 0, y: 6 }}\n          animate={{ opacity: 1, y: 0 }}\n          exit={{ opacity: 0, y: -6 }}\n          className=\"text-neutral-300\"\n        >\n          {feature.content}\n        </motion.p>\n      </AnimatePresence>\n    </div>\n  );\n}"
      }
    ]
  },
  "magnetic-button": {
    "slug": "magnetic-button",
    "overview": "MagneticButton adds a physics-based cursor attraction effect to any button or interactive element. As the cursor approaches, the element gently pulls toward it, creating a satisfying tactile feel.",
    "scenarios": [
      {
        "title": "Primary CTA button",
        "description": "Apply the magnetic effect to your hero CTA to make it irresistible to click.",
        "code": "import { MagneticButton } from \"@/components/ui/magnetic-button\";\n\nexport default function HeroCTA() {\n  return (\n    <div className=\"flex justify-center py-20\">\n      <MagneticButton>\n        <button className=\"px-8 py-4 bg-white text-black rounded-full font-semibold text-lg hover:bg-neutral-100 transition-colors\">\n          Get started free →\n        </button>\n      </MagneticButton>\n    </div>\n  );\n}"
      },
      {
        "title": "Icon navigation links",
        "description": "Magnetic icons in a header or dock feel playful and high-quality.",
        "code": "import { MagneticButton } from \"@/components/ui/magnetic-button\";\nimport { Code, X, Mail } from \"lucide-react\";\n\nconst socialLinks = [\n  { icon: Code, href: \"https://github.com\", label: \"GitHub\" },\n  { icon: X, href: \"https://twitter.com\", label: \"Twitter\" },\n  { icon: Mail, href: \"mailto:hi@example.com\", label: \"Email\" },\n];\n\nexport default function SocialNav() {\n  return (\n    <div className=\"flex items-center gap-2\">\n      {socialLinks.map(({ icon: Icon, href, label }) => (\n        <MagneticButton key={label} strength={0.4}>\n          <a\n            href={href}\n            aria-label={label}\n            className=\"p-2.5 rounded-xl border border-neutral-800 text-neutral-400 hover:text-white hover:border-neutral-600 transition-colors\"\n          >\n            <Icon className=\"w-5 h-5\" />\n          </a>\n        </MagneticButton>\n      ))}\n    </div>\n  );\n}"
      },
      {
        "title": "Reduced-strength subtle hover",
        "description": "Lower the strength for elements that should feel premium but not distracting.",
        "code": "import { MagneticButton } from \"@/components/ui/magnetic-button\";\n\nexport default function SubtleCard() {\n  return (\n    <MagneticButton strength={0.25} className=\"block\">\n      <div className=\"p-6 rounded-2xl border border-neutral-800 bg-neutral-900 cursor-pointer hover:border-neutral-700 transition-colors\">\n        <h3 className=\"text-white font-semibold mb-2\">UniqueUI Pro</h3>\n        <p className=\"text-neutral-400 text-sm\">Access all templates and premium components.</p>\n      </div>\n    </MagneticButton>\n  );\n}"
      }
    ]
  },
  "infinite-marquee": {
    "slug": "infinite-marquee",
    "overview": "InfiniteMarquee continuously scrolls a row of items horizontally, looping seamlessly. It's commonly used for logo strips, testimonial tickers, and feature highlights.",
    "scenarios": [
      {
        "title": "Client logo strip",
        "description": "Showcase trusted brand logos below the hero section to build social proof.",
        "code": "import { InfiniteMarquee } from \"@/components/ui/infinite-marquee\";\n\nconst logos = [\"Vercel\", \"Stripe\", \"Linear\", \"Notion\", \"Figma\", \"GitHub\"];\n\nexport default function LogoStrip() {\n  return (\n    <div className=\"py-12 border-y border-neutral-800\">\n      <InfiniteMarquee speed={30} gap={64}>\n        {logos.map((name) => (\n          <span key={name} className=\"text-lg font-semibold text-neutral-500 shrink-0\">\n            {name}\n          </span>\n        ))}\n      </InfiniteMarquee>\n    </div>\n  );\n}"
      },
      {
        "title": "Bidirectional feature ticker",
        "description": "Two rows scrolling in opposite directions create depth and visual interest for a features section.",
        "code": "import { InfiniteMarquee } from \"@/components/ui/infinite-marquee\";\n\nconst row1 = [\"Motion.dev springs\", \"Copy-paste DX\", \"Dark mode\", \"TypeScript-first\"];\nconst row2 = [\"Zero config\", \"Tailwind CSS v4\", \"Single-file\", \"Accessible\"];\n\nexport default function FeatureTicker() {\n  return (\n    <div className=\"space-y-3 py-10 overflow-hidden\">\n      <InfiniteMarquee speed={25} direction=\"left\">\n        {row1.map((f) => (\n          <span key={f} className=\"px-4 py-1.5 rounded-full border border-neutral-700 text-sm text-neutral-300 shrink-0\">\n            {f}\n          </span>\n        ))}\n      </InfiniteMarquee>\n      <InfiniteMarquee speed={25} direction=\"right\">\n        {row2.map((f) => (\n          <span key={f} className=\"px-4 py-1.5 rounded-full border border-purple-500/30 text-sm text-purple-300 shrink-0\">\n            {f}\n          </span>\n        ))}\n      </InfiniteMarquee>\n    </div>\n  );\n}"
      }
    ]
  },
  "scroll-reveal": {
    "slug": "scroll-reveal",
    "overview": "ScrollReveal wraps any element and fades + slides it into view when it enters the viewport using an IntersectionObserver. Zero layout shift, respects prefers-reduced-motion.",
    "scenarios": [
      {
        "title": "Staggered feature list",
        "description": "Reveal bullet points one by one as the user scrolls down a features section.",
        "code": "import { ScrollReveal } from \"@/components/ui/scroll-reveal\";\n\nconst features = [\n  \"Copy-paste single-file components\",\n  \"Motion.dev spring animations\",\n  \"Dark and light theme support\",\n  \"TypeScript-first API\",\n];\n\nexport default function FeatureList() {\n  return (\n    <ul className=\"space-y-3\">\n      {features.map((feature, i) => (\n        <ScrollReveal key={i} delay={i * 0.08}>\n          <li className=\"flex items-center gap-3 text-neutral-300\">\n            <span className=\"h-1.5 w-1.5 rounded-full bg-purple-500\" />\n            {feature}\n          </li>\n        </ScrollReveal>\n      ))}\n    </ul>\n  );\n}"
      },
      {
        "title": "Animated section headers",
        "description": "Reveal each section heading with a subtle upward drift as the user reaches it.",
        "code": "import { ScrollReveal } from \"@/components/ui/scroll-reveal\";\n\nexport default function SectionHeader({ title, subtitle }: { title: string; subtitle: string }) {\n  return (\n    <div className=\"text-center space-y-3\">\n      <ScrollReveal>\n        <h2 className=\"text-4xl font-bold text-white\">{title}</h2>\n      </ScrollReveal>\n      <ScrollReveal delay={0.1}>\n        <p className=\"text-neutral-400 max-w-xl mx-auto\">{subtitle}</p>\n      </ScrollReveal>\n    </div>\n  );\n}"
      }
    ]
  },
  "morphing-modal": {
    "slug": "morphing-modal",
    "overview": "MorphingModal animates open/close with a spring-driven scale and blur, making overlays feel fluid rather than jarring. Supports a trigger element for shared-layout animations.",
    "scenarios": [
      {
        "title": "Confirmation dialog",
        "description": "Use the modal for destructive actions — a focused modal prevents accidental clicks better than inline prompts.",
        "code": "import { MorphingModal } from \"@/components/ui/morphing-modal\";\nimport { useState } from \"react\";\n\nexport default function ConfirmDelete() {\n  const [open, setOpen] = useState(false);\n\n  return (\n    <>\n      <button\n        onClick={() => setOpen(true)}\n        className=\"px-4 py-2 bg-red-500/10 text-red-400 border border-red-500/20 rounded-lg text-sm\"\n      >\n        Delete project\n      </button>\n\n      <MorphingModal open={open} onClose={() => setOpen(false)}>\n        <div className=\"p-6 space-y-4 max-w-sm\">\n          <h2 className=\"text-lg font-semibold text-white\">Are you sure?</h2>\n          <p className=\"text-sm text-neutral-400\">\n            This will permanently delete the project and all its data. This action cannot be undone.\n          </p>\n          <div className=\"flex gap-3 pt-2\">\n            <button\n              onClick={() => setOpen(false)}\n              className=\"flex-1 py-2 rounded-lg border border-neutral-700 text-neutral-300 text-sm\"\n            >\n              Cancel\n            </button>\n            <button className=\"flex-1 py-2 rounded-lg bg-red-600 text-white text-sm font-medium\">\n              Delete\n            </button>\n          </div>\n        </div>\n      </MorphingModal>\n    </>\n  );\n}"
      },
      {
        "title": "Image / media preview",
        "description": "Expand a thumbnail into a full preview with a smooth morph transition.",
        "code": "import { MorphingModal } from \"@/components/ui/morphing-modal\";\nimport { useState } from \"react\";\n\nexport default function ImagePreview() {\n  const [open, setOpen] = useState(false);\n\n  return (\n    <>\n      <img\n        src=\"/preview-thumb.jpg\"\n        alt=\"Preview\"\n        onClick={() => setOpen(true)}\n        className=\"w-32 h-20 object-cover rounded-lg cursor-zoom-in\"\n      />\n\n      <MorphingModal open={open} onClose={() => setOpen(false)}>\n        <div className=\"p-2\">\n          <img\n            src=\"/preview-full.jpg\"\n            alt=\"Full preview\"\n            className=\"max-w-2xl w-full rounded-xl object-cover\"\n          />\n        </div>\n      </MorphingModal>\n    </>\n  );\n}"
      },
      {
        "title": "Multi-step onboarding modal",
        "description": "Use internal state to drive a step-by-step flow inside a single modal instance.",
        "code": "import { MorphingModal } from \"@/components/ui/morphing-modal\";\nimport { useState } from \"react\";\nimport { motion, AnimatePresence } from \"motion/react\";\n\nconst steps = [\"Welcome\", \"Choose plan\", \"You're ready\"];\n\nexport default function OnboardingModal({ open, onClose }: { open: boolean; onClose: () => void }) {\n  const [step, setStep] = useState(0);\n\n  return (\n    <MorphingModal open={open} onClose={onClose}>\n      <div className=\"p-8 w-full max-w-md space-y-6\">\n        <div className=\"flex gap-1.5\">\n          {steps.map((_, i) => (\n            <div\n              key={i}\n              className={`h-1 flex-1 rounded-full transition-colors ${\n                i <= step ? \"bg-purple-500\" : \"bg-neutral-700\"\n              }`}\n            />\n          ))}\n        </div>\n\n        <AnimatePresence mode=\"wait\">\n          <motion.div\n            key={step}\n            initial={{ opacity: 0, x: 12 }}\n            animate={{ opacity: 1, x: 0 }}\n            exit={{ opacity: 0, x: -12 }}\n            className=\"space-y-2\"\n          >\n            <h2 className=\"text-xl font-bold text-white\">{steps[step]}</h2>\n            <p className=\"text-sm text-neutral-400\">Step {step + 1} of {steps.length}</p>\n          </motion.div>\n        </AnimatePresence>\n\n        <button\n          onClick={() => step < steps.length - 1 ? setStep(s => s + 1) : onClose()}\n          className=\"w-full py-2.5 bg-purple-600 text-white rounded-xl font-medium\"\n        >\n          {step < steps.length - 1 ? \"Continue\" : \"Finish\"}\n        </button>\n      </div>\n    </MorphingModal>\n  );\n}"
      }
    ]
  },
  "gradient-text-reveal": {
    "slug": "gradient-text-reveal",
    "overview": "GradientTextReveal animates a gradient sweep across text as it enters the viewport — a dramatic way to introduce headlines or key phrases on scroll.",
    "scenarios": [
      {
        "title": "Section headline reveal",
        "description": "Fire the reveal when the section scrolls into view for a cinematic entrance.",
        "code": "import { GradientTextReveal } from \"@/components/ui/gradient-text-reveal\";\n\nexport default function SectionHeadline() {\n  return (\n    <div className=\"py-24 text-center\">\n      <GradientTextReveal\n        text=\"Design that moves people.\"\n        className=\"text-5xl font-bold\"\n        gradient=\"from-white via-purple-300 to-white\"\n      />\n    </div>\n  );\n}"
      },
      {
        "title": "Pull quote in a blog post",
        "description": "Highlight a key quote mid-article with a gradient sweep to re-engage readers.",
        "code": "import { GradientTextReveal } from \"@/components/ui/gradient-text-reveal\";\n\nexport default function PullQuote() {\n  return (\n    <blockquote className=\"my-12 px-8 border-l-2 border-purple-500\">\n      <GradientTextReveal\n        text=\"The best design is invisible — until it moves.\"\n        className=\"text-2xl font-medium italic\"\n        gradient=\"from-neutral-300 via-purple-400 to-neutral-300\"\n        duration={1.4}\n      />\n    </blockquote>\n  );\n}"
      }
    ]
  },
  "floating-dock": {
    "slug": "floating-dock",
    "overview": "FloatingDock renders a macOS-style icon dock with a magnetic magnification effect. Icons near the cursor scale up smoothly, making navigation feel interactive and playful.",
    "scenarios": [
      {
        "title": "App bottom navigation",
        "description": "Replace a static mobile nav bar with a floating dock for a more expressive feel.",
        "code": "import { FloatingDock } from \"@/components/ui/floating-dock\";\nimport { Home, Search, Bell, User, Settings } from \"lucide-react\";\n\nconst navItems = [\n  { title: \"Home\", icon: <Home className=\"w-5 h-5\" />, href: \"/\" },\n  { title: \"Search\", icon: <Search className=\"w-5 h-5\" />, href: \"/search\" },\n  { title: \"Notifications\", icon: <Bell className=\"w-5 h-5\" />, href: \"/notifications\" },\n  { title: \"Profile\", icon: <User className=\"w-5 h-5\" />, href: \"/profile\" },\n  { title: \"Settings\", icon: <Settings className=\"w-5 h-5\" />, href: \"/settings\" },\n];\n\nexport default function AppNav() {\n  return (\n    <div className=\"fixed bottom-8 left-1/2 -translate-x-1/2 z-50\">\n      <FloatingDock items={navItems} />\n    </div>\n  );\n}"
      },
      {
        "title": "Social media quick-share dock",
        "description": "A share toolbar that floats alongside article content for quick social sharing.",
        "code": "import { FloatingDock } from \"@/components/ui/floating-dock\";\nimport { X, Globe, Link2, Bookmark } from \"lucide-react\";\n\nconst shareItems = [\n  { title: \"Share on X\", icon: <X className=\"w-5 h-5\" />, href: \"#\" },\n  { title: \"Share on LinkedIn\", icon: <Globe className=\"w-5 h-5\" />, href: \"#\" },\n  { title: \"Copy link\", icon: <Link2 className=\"w-5 h-5\" />, href: \"#\" },\n  { title: \"Bookmark\", icon: <Bookmark className=\"w-5 h-5\" />, href: \"#\" },\n];\n\nexport default function ShareDock() {\n  return (\n    <aside className=\"fixed right-6 top-1/2 -translate-y-1/2 hidden lg:block\">\n      <FloatingDock items={shareItems} direction=\"vertical\" />\n    </aside>\n  );\n}"
      },
      {
        "title": "Document editor toolbar",
        "description": "A compact formatting toolbar with magnification for a rich-text or canvas editor.",
        "code": "import { FloatingDock } from \"@/components/ui/floating-dock\";\nimport { Bold, Italic, Underline, AlignLeft, AlignCenter, List, Image } from \"lucide-react\";\n\nconst toolbarItems = [\n  { title: \"Bold\", icon: <Bold className=\"w-4 h-4\" />, href: \"#\" },\n  { title: \"Italic\", icon: <Italic className=\"w-4 h-4\" />, href: \"#\" },\n  { title: \"Underline\", icon: <Underline className=\"w-4 h-4\" />, href: \"#\" },\n  { title: \"Align left\", icon: <AlignLeft className=\"w-4 h-4\" />, href: \"#\" },\n  { title: \"Center\", icon: <AlignCenter className=\"w-4 h-4\" />, href: \"#\" },\n  { title: \"List\", icon: <List className=\"w-4 h-4\" />, href: \"#\" },\n  { title: \"Image\", icon: <Image className=\"w-4 h-4\" />, href: \"#\" },\n];\n\nexport default function EditorToolbar() {\n  return (\n    <div className=\"flex justify-center py-4\">\n      <FloatingDock items={toolbarItems} magnification={52} distance={100} />\n    </div>\n  );\n}"
      }
    ]
  },
  "confetti-burst": {
    "slug": "confetti-burst",
    "overview": "ConfettiBurst fires a particle explosion from a point on screen — perfect for celebrating milestones like a completed form, a successful payment, or an unlocked achievement.",
    "scenarios": [
      {
        "title": "Success after form submission",
        "description": "Trigger a confetti burst when the user completes a sign-up or checkout form.",
        "code": "import { ConfettiBurst } from \"@/components/ui/confetti-burst\";\nimport { useState } from \"react\";\n\nexport default function SignupForm() {\n  const [submitted, setSubmitted] = useState(false);\n  const [triggerConfetti, setTriggerConfetti] = useState(false);\n\n  const handleSubmit = (e: React.FormEvent) => {\n    e.preventDefault();\n    setSubmitted(true);\n    setTriggerConfetti(true);\n    setTimeout(() => setTriggerConfetti(false), 100);\n  };\n\n  return (\n    <div className=\"relative\">\n      {submitted ? (\n        <div className=\"text-center text-white py-8\">\n          <p className=\"text-2xl font-bold\">You're in! 🎉</p>\n        </div>\n      ) : (\n        <form onSubmit={handleSubmit} className=\"space-y-4\">\n          <input type=\"email\" placeholder=\"Your email\" className=\"w-full px-4 py-2.5 rounded-xl bg-neutral-900 border border-neutral-700 text-white\" />\n          <button type=\"submit\" className=\"w-full py-3 bg-purple-600 text-white rounded-xl font-semibold\">\n            Join waitlist\n          </button>\n        </form>\n      )}\n      <ConfettiBurst trigger={triggerConfetti} origin={{ x: 0.5, y: 0.5 }} />\n    </div>\n  );\n}"
      },
      {
        "title": "Achievement unlock",
        "description": "Celebrate when a user reaches a milestone inside a dashboard or onboarding flow.",
        "code": "import { ConfettiBurst } from \"@/components/ui/confetti-burst\";\nimport { useState } from \"react\";\nimport { Trophy } from \"lucide-react\";\n\nexport default function AchievementCard() {\n  const [unlocked, setUnlocked] = useState(false);\n  const [burst, setBurst] = useState(false);\n\n  const unlock = () => {\n    setUnlocked(true);\n    setBurst(true);\n    setTimeout(() => setBurst(false), 100);\n  };\n\n  return (\n    <div className=\"relative p-6 rounded-2xl border border-neutral-800 bg-neutral-900 text-center space-y-4\">\n      <Trophy className={`w-10 h-10 mx-auto transition-colors ${unlocked ? \"text-yellow-400\" : \"text-neutral-600\"}`} />\n      <p className=\"text-white font-semibold\">First component added</p>\n      {!unlocked && (\n        <button onClick={unlock} className=\"px-5 py-2 bg-purple-600 text-white rounded-xl text-sm font-medium\">\n          Claim reward\n        </button>\n      )}\n      <ConfettiBurst trigger={burst} particleCount={80} />\n    </div>\n  );\n}"
      }
    ]
  },
  "notification-stack": {
    "slug": "notification-stack",
    "overview": "NotificationStack renders a stacked pile of toast-style cards that animate in and collapse when dismissed. Great for live activity feeds, system alerts, or social notifications.",
    "scenarios": [
      {
        "title": "Live activity feed",
        "description": "Push real-time events (new users, payments, deployments) into the stack.",
        "code": "import { NotificationStack } from \"@/components/ui/notification-stack\";\nimport { useState } from \"react\";\n\nconst events = [\n  { id: 1, title: \"New signup\", body: \"prashant@example.com just joined.\" },\n  { id: 2, title: \"Payment received\", body: \"$49 from Stripe · Order #1042\" },\n  { id: 3, title: \"Deploy success\", body: \"main → production in 34s\" },\n];\n\nexport default function ActivityFeed() {\n  const [notifications, setNotifications] = useState(events);\n\n  return (\n    <NotificationStack\n      notifications={notifications}\n      onDismiss={(id) => setNotifications((n) => n.filter((x) => x.id !== id))}\n    />\n  );\n}"
      },
      {
        "title": "Form validation errors",
        "description": "Surface validation errors as dismissible stacked notices instead of inline messages.",
        "code": "import { NotificationStack } from \"@/components/ui/notification-stack\";\n\nconst errors = [\n  { id: 1, title: \"Email required\", body: \"Please enter a valid email address.\" },\n  { id: 2, title: \"Password too short\", body: \"Password must be at least 8 characters.\" },\n];\n\nexport default function FormErrors() {\n  return (\n    <div className=\"fixed bottom-6 right-6 z-50 w-80\">\n      <NotificationStack notifications={errors} variant=\"error\" />\n    </div>\n  );\n}"
      }
    ]
  },
  "bento-grid": {
    "slug": "bento-grid",
    "overview": "BentoGrid lays out content cards in an asymmetric masonry-style grid inspired by Apple's design language. Each cell can span multiple columns or rows, with animated entrance and hover effects.",
    "scenarios": [
      {
        "title": "Product feature overview",
        "description": "Showcase multiple features in a single glanceable grid without overwhelming the user.",
        "code": "import { BentoGrid, BentoCard } from \"@/components/ui/bento-grid\";\nimport { Zap, Shield, Code } from \"lucide-react\";\n\nexport default function FeatureGrid() {\n  return (\n    <BentoGrid>\n      <BentoCard\n        title=\"Blazing fast\"\n        description=\"Server-side rendered with zero layout shift.\"\n        icon={<Zap className=\"w-6 h-6\" />}\n        className=\"col-span-2\"\n      />\n      <BentoCard\n        title=\"Type-safe\"\n        description=\"Full TypeScript support out of the box.\"\n        icon={<Code className=\"w-6 h-6\" />}\n      />\n      <BentoCard\n        title=\"Secure by default\"\n        description=\"No external requests. Your data stays local.\"\n        icon={<Shield className=\"w-6 h-6\" />}\n      />\n    </BentoGrid>\n  );\n}"
      },
      {
        "title": "Personal portfolio grid",
        "description": "Display projects, skills, and social links in an editorial bento layout.",
        "code": "import { BentoGrid, BentoCard } from \"@/components/ui/bento-grid\";\n\nexport default function PortfolioGrid() {\n  return (\n    <BentoGrid className=\"max-w-4xl mx-auto\">\n      <BentoCard\n        title=\"UniqueUI\"\n        description=\"An open-source animated component library.\"\n        className=\"col-span-2 row-span-2\"\n      />\n      <BentoCard title=\"React\" description=\"5 years\" />\n      <BentoCard title=\"Next.js\" description=\"3 years\" />\n      <BentoCard\n        title=\"Open to work\"\n        description=\"Based in India · Remote-friendly\"\n        className=\"col-span-2\"\n      />\n    </BentoGrid>\n  );\n}"
      }
    ]
  },
  "glow-hero-section": {
    "slug": "glow-hero-section",
    "overview": "GlowHeroSection is a full-width hero component with a customizable radial glow effect behind the content. It combines a gradient background, centered text hierarchy, and optional CTA buttons into one production-ready section.",
    "scenarios": [
      {
        "title": "SaaS product landing hero",
        "description": "The most common pattern — headline, subheadline, and two CTA buttons over a dark glowing background.",
        "code": "import GlowHeroSection from \"@/components/ui/glow-hero-section\";\nimport Link from \"next/link\";\n\nexport default function LandingHero() {\n  return (\n    <GlowHeroSection\n      badge=\"Now in public beta\"\n      title=\"Ship cinematic UI in minutes\"\n      subtitle=\"Copy-paste animated React components powered by motion.dev and Tailwind CSS.\"\n      glowColor=\"purple\"\n    >\n      <div className=\"flex gap-4 justify-center mt-8\">\n        <Link href=\"/components\" className=\"px-7 py-3.5 bg-white text-black rounded-full font-semibold\">\n          Browse components\n        </Link>\n        <a href=\"https://github.com/pras75299/uniqueui\" className=\"px-7 py-3.5 border border-neutral-700 text-white rounded-full\">\n          Star on GitHub\n        </a>\n      </div>\n    </GlowHeroSection>\n  );\n}"
      },
      {
        "title": "Open-source project hero",
        "description": "Show contributor count and GitHub stars as social proof badges inside the glow hero.",
        "code": "import GlowHeroSection from \"@/components/ui/glow-hero-section\";\nimport { Star, Users } from \"lucide-react\";\n\nexport default function OpenSourceHero() {\n  return (\n    <GlowHeroSection\n      title=\"Built in the open.\"\n      subtitle=\"Every component is MIT-licensed and community-maintained.\"\n      glowColor=\"blue\"\n    >\n      <div className=\"flex gap-4 justify-center mt-6\">\n        <span className=\"flex items-center gap-1.5 text-sm border border-neutral-700 rounded-full px-4 py-1.5 text-neutral-300\">\n          <Star className=\"w-4 h-4 text-yellow-400\" /> 2.4k stars\n        </span>\n        <span className=\"flex items-center gap-1.5 text-sm border border-neutral-700 rounded-full px-4 py-1.5 text-neutral-300\">\n          <Users className=\"w-4 h-4 text-blue-400\" /> 120 contributors\n        </span>\n      </div>\n    </GlowHeroSection>\n  );\n}"
      }
    ]
  },
  "shiny-text": {
    "slug": "shiny-text",
    "overview": "ShinyText adds a moving shimmer highlight that sweeps across your text using a CSS background-clip animation. Ideal for hero taglines, badge labels, or any copy that needs a premium metallic feel.",
    "scenarios": [
      {
        "title": "Hero tagline highlight",
        "description": "Draw attention to a key phrase in your hero section with a continuous shimmer sweep.",
        "code": "import { ShinyText } from \"@/components/ui/shiny-text\";\n\nexport default function HeroTagline() {\n  return (\n    <h1 className=\"text-5xl font-bold text-white\">\n      Build beautiful UIs{\" \"}\n      <ShinyText text=\"effortlessly\" speed={2.5} className=\"text-purple-400\" />\n    </h1>\n  );\n}"
      },
      {
        "title": "Premium badge label",
        "description": "Use a smaller shimmer span inside a pill badge to signal a paid or featured tier.",
        "code": "import { ShinyText } from \"@/components/ui/shiny-text\";\n\nexport default function PremiumBadge() {\n  return (\n    <span className=\"inline-flex items-center gap-1.5 px-3 py-1 rounded-full border border-yellow-500/30 bg-yellow-500/10 text-xs font-semibold\">\n      ✦ <ShinyText text=\"PRO\" speed={4} className=\"text-yellow-400\" />\n    </span>\n  );\n}"
      },
      {
        "title": "CTA button text",
        "description": "Give a call-to-action button a shimmering label to make it pop on dark landing pages.",
        "code": "import { ShinyText } from \"@/components/ui/shiny-text\";\n\nexport default function ShinyButton() {\n  return (\n    <button className=\"px-6 py-3 rounded-xl bg-neutral-800 border border-neutral-700 hover:border-purple-500 transition-colors\">\n      <ShinyText text=\"Get started for free →\" speed={3} className=\"text-white\" />\n    </button>\n  );\n}"
      }
    ]
  },
  "blur-reveal": {
    "slug": "blur-reveal",
    "overview": "BlurReveal staggers a blur-fade-in animation across each character or word as the element enters the viewport. It creates an elegant reveal effect perfect for hero text and section headings.",
    "scenarios": [
      {
        "title": "Hero heading entrance",
        "description": "Animate your primary headline character-by-character as the page loads.",
        "code": "import { BlurReveal } from \"@/components/ui/blur-reveal\";\n\nexport default function HeroHeading() {\n  return (\n    <h1 className=\"text-6xl font-bold text-white\">\n      <BlurReveal text=\"Ship faster.\" animateBy=\"characters\" duration={0.5} />\n    </h1>\n  );\n}"
      },
      {
        "title": "Section subtitle word reveal",
        "description": "Reveal a section subtitle word-by-word for a slightly slower, more dramatic effect.",
        "code": "import { BlurReveal } from \"@/components/ui/blur-reveal\";\n\nexport default function SectionSubtitle() {\n  return (\n    <p className=\"text-xl text-neutral-400 max-w-xl\">\n      <BlurReveal\n        text=\"Beautifully crafted components that make your UI stand out.\"\n        animateBy=\"words\"\n        delay={0.1}\n        duration={0.7}\n      />\n    </p>\n  );\n}"
      }
    ]
  },
  "count-up": {
    "slug": "count-up",
    "overview": "CountUp animates a number from a starting value to a target value as it enters the viewport. It supports decimals, prefixes, suffixes, and thousands separators — perfect for stats and metrics sections.",
    "scenarios": [
      {
        "title": "Stats row",
        "description": "Display key product metrics that animate in when the user scrolls to them.",
        "code": "import { CountUp } from \"@/components/ui/count-up\";\n\nconst stats = [\n  { label: \"Components\", value: 60, suffix: \"+\" },\n  { label: \"GitHub Stars\", value: 4.2, suffix: \"k\", decimals: 1 },\n  { label: \"Downloads\", value: 120, suffix: \"k+\" },\n];\n\nexport default function StatsRow() {\n  return (\n    <div className=\"grid grid-cols-3 gap-8 text-center\">\n      {stats.map(({ label, value, suffix, decimals }) => (\n        <div key={label}>\n          <p className=\"text-4xl font-bold text-white\">\n            <CountUp to={value} suffix={suffix} decimals={decimals} />\n          </p>\n          <p className=\"text-sm text-neutral-400 mt-1\">{label}</p>\n        </div>\n      ))}\n    </div>\n  );\n}"
      },
      {
        "title": "Revenue counter with currency prefix",
        "description": "Show an animated revenue or savings figure with a dollar sign prefix.",
        "code": "import { CountUp } from \"@/components/ui/count-up\";\n\nexport default function RevenueCounter() {\n  return (\n    <div className=\"text-center space-y-1\">\n      <p className=\"text-5xl font-extrabold text-emerald-400\">\n        <CountUp from={0} to={1250000} prefix=\"$\" separator=\",\" duration={2.5} />\n      </p>\n      <p className=\"text-sm text-neutral-400\">Total revenue generated</p>\n    </div>\n  );\n}"
      }
    ]
  },
  "border-beam": {
    "slug": "border-beam",
    "overview": "BorderBeam traces an animated glowing orb around the perimeter of any container using requestAnimationFrame. Wrap any card, input, or panel to give it a dynamic, premium border highlight.",
    "scenarios": [
      {
        "title": "Glowing feature card",
        "description": "Wrap a feature card so a colorful beam traces its border continuously.",
        "code": "import { BorderBeam } from \"@/components/ui/border-beam\";\n\nexport default function FeatureCard() {\n  return (\n    <BorderBeam colorFrom=\"#a855f7\" colorTo=\"#06b6d4\" duration={4}>\n      <div className=\"p-6 rounded-2xl bg-neutral-900 space-y-2\">\n        <h3 className=\"text-lg font-semibold text-white\">Motion-powered</h3>\n        <p className=\"text-sm text-neutral-400\">\n          Every animation uses spring physics for natural, fluid movement.\n        </p>\n      </div>\n    </BorderBeam>\n  );\n}"
      },
      {
        "title": "Highlighted input field",
        "description": "Give a search or email input an animated border beam to draw focus.",
        "code": "import { BorderBeam } from \"@/components/ui/border-beam\";\n\nexport default function BeamInput() {\n  return (\n    <BorderBeam colorFrom=\"#f59e0b\" colorTo=\"#ef4444\" borderWidth={2} duration={3}>\n      <input\n        type=\"email\"\n        placeholder=\"Enter your email\"\n        className=\"w-full px-4 py-3 rounded-xl bg-neutral-800 text-white outline-none text-sm\"\n      />\n    </BorderBeam>\n  );\n}"
      }
    ]
  },
  "ripple": {
    "slug": "ripple",
    "overview": "Ripple renders concentric animated rings that pulse outward from a center point. Use it as a background for icons, avatars, or buttons to convey activity, presence, or emphasis.",
    "scenarios": [
      {
        "title": "Live presence indicator",
        "description": "Show a pulsing ripple behind an avatar to indicate a user is online or broadcasting.",
        "code": "import { Ripple } from \"@/components/ui/ripple\";\n\nexport default function LivePresence() {\n  return (\n    <div className=\"relative flex items-center justify-center w-24 h-24\">\n      <Ripple mainCircleSize={48} numCircles={5} color=\"#22c55e\" duration={2.5} />\n      <img\n        src=\"/avatar.png\"\n        alt=\"User\"\n        className=\"relative z-10 w-12 h-12 rounded-full border-2 border-green-500\"\n      />\n    </div>\n  );\n}"
      },
      {
        "title": "CTA focus ring",
        "description": "Add a ripple effect behind a primary CTA button to make it visually magnetic.",
        "code": "import { Ripple } from \"@/components/ui/ripple\";\n\nexport default function RippleCTA() {\n  return (\n    <div className=\"relative inline-flex items-center justify-center\">\n      <Ripple mainCircleSize={64} numCircles={4} color=\"#a855f7\" duration={3} />\n      <button className=\"relative z-10 px-6 py-3 bg-purple-600 text-white rounded-xl font-semibold text-sm\">\n        Get Started\n      </button>\n    </div>\n  );\n}"
      }
    ]
  },
  "word-rotate": {
    "slug": "word-rotate",
    "overview": "WordRotate cycles through an array of words with configurable entrance and exit animations — slide, flip, or fade. Drop it inline within headings to convey multiple ideas without extra layout space.",
    "scenarios": [
      {
        "title": "Hero headline value rotator",
        "description": "Cycle through your product's core benefits inline inside a headline.",
        "code": "import { WordRotate } from \"@/components/ui/word-rotate\";\n\nexport default function HeroHeadline() {\n  return (\n    <h1 className=\"text-5xl font-bold text-white\">\n      The{\" \"}\n      <WordRotate\n        words={[\"fastest\", \"cleanest\", \"smartest\"]}\n        animation=\"slide-up\"\n        className=\"text-purple-400\"\n      />\n      {\" \"}way to ship UI\n    </h1>\n  );\n}"
      },
      {
        "title": "Feature list rotator with flip",
        "description": "Use the flip animation for a more dramatic 3-D card-turning effect.",
        "code": "import { WordRotate } from \"@/components/ui/word-rotate\";\n\nexport default function FlipRotator() {\n  return (\n    <p className=\"text-2xl font-semibold text-white\">\n      Built for{\" \"}\n      <WordRotate\n        words={[\"designers\", \"developers\", \"startups\", \"agencies\"]}\n        animation=\"flip\"\n        interval={2000}\n        className=\"text-emerald-400\"\n      />\n    </p>\n  );\n}"
      },
      {
        "title": "Subtle fade rotator in body copy",
        "description": "Use the fade animation for a soft, unobtrusive rotation inside a paragraph.",
        "code": "import { WordRotate } from \"@/components/ui/word-rotate\";\n\nexport default function FadeRotator() {\n  return (\n    <p className=\"text-base text-neutral-400\">\n      Perfect for{\" \"}\n      <WordRotate\n        words={[\"landing pages\", \"SaaS apps\", \"portfolios\", \"dashboards\"]}\n        animation=\"fade\"\n        interval={3000}\n        className=\"text-white font-medium\"\n      />\n    </p>\n  );\n}"
      }
    ]
  }
};
